### ISSUE TITLE
Alternative clipboard feature package

### ISSUE THREAD

**Issue by pdeffebach** [JuliaActuary/ActuaryUtilities.jl#41]
Hello!

I really like the functions `xlcopy()` and `xlcopy(data)`. I think it's really awesome to have such easy interoperability with excel. 

They seem so important that they probably shouldn't live in a domain-specific package like ActuaryUtilities. Everyone, even non-actuaries, should use this feature. 

So I've created [ClipboardCSV](https://github.com/pdeffebach/ClipboardCSV) which takes some of the core features from `xlcopy` and puts them in a standalone package. Here are some examples of how it works

```julia
julia> using DataFrames, ClipboardCSV

julia> df = DataFrame(a = [1, 2], b = [3, 4], c = [5, 6], d = [7, 8])
2×4 DataFrame
 Row │ a      b      c      d     
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     1      3      5      7
   2 │     2      4      6      8

julia> tabletoclip(df)
a,b,c,d
1,3,5,7
2,4,6,8


julia> cliptotable()
2-element CSV.File{false}:
 CSV.Row: (a = 1, b = 3, c = 5, d = 7)
 CSV.Row: (a = 2, b = 4, c = 6, d = 8)

julia> @tabletomwe df
df = """
a,b,c,d
1,3,5,7
2,4,6,8
""" |> IOBuffer |> CSV.File |> DataFrame



julia> eval(first(Meta.parse(clipboard(), 1)))
2×4 DataFrame
 Row │ a      b      c      d     
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     1      3      5      7
   2 │     2      4      6      8

```

This package is not yet mature. It needs tests, a few more features, and documentation. However when all that is done and the package is released, would you consider deprecating `xlcopy` and taking ClipboardCSV.jl as a dependency?

**Comment by alecloudenback** [comment]
Hey, thanks for the feedback - I had actually already split out the functionaluty based on some [community feedback](https://discourse.julialang.org/t/ann-excelutilities-jl/55907) into [ExcelUtilities.jl](https://github.com/alecloudenback/ExcelUtilities.jl). And it's on the to-do list (#33) to directly use that dependency here.

I think that some of the ideas you have are very interesting - do you mind taking a look at ExcelUtilities.jl and then copying this issue over there for further discussion?
