### ISSUE TITLE
Organize Doc Page

### ISSUE THREAD

**Issue by alecloudenback** [JuliaActuary/ActuaryUtilities.jl#85]
Follow same sections as README?

**Comment by xlxs4** [comment]
Hi @alecloudenback! I could take this up. Any pointers?

**Comment by xlxs4** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/54778816/195865883-65373713-9161-435f-a09d-7f16d004251d.png)

![image](https://user-images.githubusercontent.com/54778816/195865968-8f7e5db2-36bb-42d8-a761-54edbbfe22eb.png)

**Comment by alecloudenback** [comment]
Yes, that's great
